function [tdat, Dreduc_opts] = func_tsne(Dat_Pre, opts)

    if isempty(Dat_Pre)
        Dreduc_opts = cell(6,2);
        tdat = [];
        % Options for t-SNE
        Dreduc_opts(:,1) = {'Distance', ...
            'Algorithm', ...
            'Exaggeration', ...
            'Perplexity', ...
            'Theta', ...
            'Channel Name'};
        % Defaults
        Dreduc_opts(:,2) = {'euclidean', ...
            'barneshut', ...
            '4', ...
            '30', ...
            '0.5', ...
            opts};


        dlg_title = 'Options';
        num_lines = 1;
        vAnswer = inputdlg(Dreduc_opts(:,1),dlg_title,num_lines,Dreduc_opts(:,2));
        if isempty(vAnswer)
            tdat = 1;
            return
        end
        Dreduc_opts(:,2) = vAnswer;

    else
        Dreduc_opts = opts;
        % If X,Y,Z were included this breaks

        % Use t-sne to reduce the data to 2D
        tdat = tsne(Dat_Pre, ...
                    Dreduc_opts{1, 1}, Dreduc_opts{1, 2}, ...
                    Dreduc_opts{2, 1}, Dreduc_opts{2, 2}, ...
                    Dreduc_opts{3, 1}, str2double(Dreduc_opts{3, 2}), ...
                    Dreduc_opts{4, 1}, str2double(Dreduc_opts{4, 2}), ...
                    Dreduc_opts{5, 1}, str2double(Dreduc_opts{5, 2}), ...
                    'NumPCAComponents', 0);%<change back to 0
    end
                        